name: flutter_lab_support_incidents
description: Sistema de Gestión de Incidentes de Laboratorio - Universidad Privada de Tacna
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase Core
  firebase_core: ^2.24.2
  
  # Firebase Authentication
  firebase_auth: ^4.15.3
  
  # Google Sign In
  google_sign_in: ^6.1.6
  
  # Cloud Firestore (para almacenar incidentes)
  cloud_firestore: ^4.13.6
  
  # Firebase Storage (para almacenar imágenes/videos)
  firebase_storage: ^11.5.6
  
  # Image Picker (para capturar fotos/videos)
  image_picker: ^1.0.7
  
  # Permisos
  permission_handler: ^11.0.1
  
  # Iconos de Cupertino
  cupertino_icons: ^1.0.6
  
  # Manejo de estados (opcional, pero recomendado)
  provider: ^6.1.1
  
  # Para formatear fechas
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # Puedes agregar assets aquí si tienes el logo de la UPT
  # assets:
  #   - assets/images/logo_upt.png
  
  # Fuentes personalizadas (opcional)
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
  #       - asset: fonts/CustomFont-Bold.ttf
  #         weight: 700