// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEe2IzmuvVtxmsie6d-9I4SNF8Vi4S3l0',
    appId: '1:63833424445:web:c3409999158aee5385a054',
    messagingSenderId: '63833424445',
    projectId: 'upt-lab-support-incidents',
    authDomain: 'upt-lab-support-incidents.firebaseapp.com',
    storageBucket: 'upt-lab-support-incidents.firebasestorage.app',
    measurementId: 'G-DMRBMRYEL0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGBxhAf2KEjiDFNvC__djdeozZ-aLAdE8',
    appId: '1:63833424445:android:c1c432b07b17e17985a054',
    messagingSenderId: '63833424445',
    projectId: 'upt-lab-support-incidents',
    storageBucket: 'upt-lab-support-incidents.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU02Q6TIBlJ-naqgOuqciu4mHYp1JjTWY',
    appId: '1:63833424445:ios:deb6ffed514a432485a054',
    messagingSenderId: '63833424445',
    projectId: 'upt-lab-support-incidents',
    storageBucket: 'upt-lab-support-incidents.firebasestorage.app',
    iosClientId: '63833424445-7bogvi0b59bc9huj2g3805u83g8pb6kg.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLabSupportIncidents',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU02Q6TIBlJ-naqgOuqciu4mHYp1JjTWY',
    appId: '1:63833424445:ios:deb6ffed514a432485a054',
    messagingSenderId: '63833424445',
    projectId: 'upt-lab-support-incidents',
    storageBucket: 'upt-lab-support-incidents.firebasestorage.app',
    iosClientId: '63833424445-7bogvi0b59bc9huj2g3805u83g8pb6kg.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLabSupportIncidents',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEe2IzmuvVtxmsie6d-9I4SNF8Vi4S3l0',
    appId: '1:63833424445:web:00feda7ee4a91a2a85a054',
    messagingSenderId: '63833424445',
    projectId: 'upt-lab-support-incidents',
    authDomain: 'upt-lab-support-incidents.firebaseapp.com',
    storageBucket: 'upt-lab-support-incidents.firebasestorage.app',
    measurementId: 'G-9E5Q3M4W8Z',
  );
}
