// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjZuLaGsxcWAhOwDT9MCl8ctlOn_ekGR4',
    appId: '1:649968119165:web:72daca41a3df64cf317014',
    messagingSenderId: '649968119165',
    projectId: 'upt-lab-support-incident-eeba9',
    authDomain: 'upt-lab-support-incident-eeba9.firebaseapp.com',
    storageBucket: 'upt-lab-support-incident-eeba9.firebasestorage.app',
    measurementId: 'G-V1MNSV0010',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNgJGrpwAbuHzxJwLLfk_QyEl5fRmnAaA',
    appId: '1:649968119165:android:f35ab1bfe75dc87a317014',
    messagingSenderId: '649968119165',
    projectId: 'upt-lab-support-incident-eeba9',
    storageBucket: 'upt-lab-support-incident-eeba9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8kMnBq0VPyTOM9hVQhHSbPWsUkx6QiHU',
    appId: '1:649968119165:ios:76f1dfddb52dc93c317014',
    messagingSenderId: '649968119165',
    projectId: 'upt-lab-support-incident-eeba9',
    storageBucket: 'upt-lab-support-incident-eeba9.firebasestorage.app',
    iosClientId: '649968119165-pk200iqosl5j6m7jv1rhugn7ospakde3.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLabSupportIncidents',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8kMnBq0VPyTOM9hVQhHSbPWsUkx6QiHU',
    appId: '1:649968119165:ios:76f1dfddb52dc93c317014',
    messagingSenderId: '649968119165',
    projectId: 'upt-lab-support-incident-eeba9',
    storageBucket: 'upt-lab-support-incident-eeba9.firebasestorage.app',
    iosClientId: '649968119165-pk200iqosl5j6m7jv1rhugn7ospakde3.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLabSupportIncidents',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjZuLaGsxcWAhOwDT9MCl8ctlOn_ekGR4',
    appId: '1:649968119165:web:74c3c5f509e49d80317014',
    messagingSenderId: '649968119165',
    projectId: 'upt-lab-support-incident-eeba9',
    authDomain: 'upt-lab-support-incident-eeba9.firebaseapp.com',
    storageBucket: 'upt-lab-support-incident-eeba9.firebasestorage.app',
    measurementId: 'G-WT8BC3SETT',
  );

}